[LOG]: sync up with origin/master
M	trevari/cron_log/cron_job_2019_08_16_01:00.log
브랜치가 'origin/master'에 맞게 업데이트된 상태입니다.
[LOG]: get_trevari_books.py is executed on 11:00:04
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
[LOG]: get_trevari_books.py is finished on 12:58:16.
[LOG]: diff: diff --git a/trevari/trevari_book_list.md b/trevari/trevari_book_list.md
[LOG]: dir: /home/ubuntu/project/web_crawlers/trevari pwd: /home/ubuntu/project/web_crawlers/trevari
[master af2c5ef] script: trevari: update book list on  (auto generated commit)
 3 files changed, 40 insertions(+), 12 deletions(-)
 create mode 100644 trevari/cron_log/cron_job_2019_08_16_11:00.log
[LOG]: update commit - script: trevari: update book list on 2019-08-16, 12:58:21
