[LOG]: sync up with origin/master
M	trevari/cron_log/cron_job_2019_11_30_01:00.log
M	trevari/trevari_book_list.md
브랜치가 'origin/master'에 맞게 업데이트된 상태입니다.
[LOG]: get_trevari_books.py is executed on 20:00:10
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
[LOG]: get_trevari_books.py is finished on 04:01:22.
[LOG]: diff: 이진파일 (표준 입력) 와(과) 일치
[LOG]: dir: /home/ubuntu/project/web_crawlers/trevari pwd: /home/ubuntu/project/web_crawlers/trevari
[master d634a81] script: trevari: update book list on  (auto generated commit)
 4 files changed, 101 insertions(+), 7 deletions(-)
 create mode 100644 trevari/cron_log/cron_job_2019_12_01_01:00.log
[LOG]: update commit - script: trevari: update book list on 2019-12-01, 04:01:35
