[LOG]: sync up with origin/master
M	trevari/cron_log/cron_job_2019_12_18_11:00.log
M	trevari/trevari_book_list.md
브랜치가 'origin/master'에 맞게 업데이트된 상태입니다.
[LOG]: get_trevari_books.py is executed on 01:00:12
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
[LOG]: get_trevari_books.py is finished on 08:44:19.
[LOG]: diff: 이진파일 (표준 입력) 와(과) 일치
[LOG]: dir: /home/ubuntu/project/web_crawlers/trevari pwd: /home/ubuntu/project/web_crawlers/trevari
[master 7cd67c4] script: trevari: update book list on  (auto generated commit)
 3 files changed, 120 insertions(+), 1 deletion(-)
[LOG]: update commit - script: trevari: update book list on 2019-12-19, 08:44:25
