[LOG]: sync up with origin/master
M	trevari/cron_log/cron_job_2019_12_04_11:00.log
M	trevari/trevari_book_list.md
브랜치가 'origin/master'에 맞게 업데이트된 상태입니다.
[LOG]: get_trevari_books.py is executed on 11:00:14
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
[LOG]: get_trevari_books.py is finished on 17:22:44.
[LOG]: diff: diff --git a/trevari/trevari_book_list.md b/trevari/trevari_book_list.md
Binary files a/trevari/trevari_book_list.md and b/trevari/trevari_book_list.md differ
[LOG]: dir: /home/ubuntu/project/web_crawlers/trevari pwd: /home/ubuntu/project/web_crawlers/trevari
[master b221f17] script: trevari: update book list on  (auto generated commit)
 4 files changed, 160 insertions(+), 1 deletion(-)
[LOG]: update commit - script: trevari: update book list on 2019-12-05, 17:22:55
