[LOG]: sync up with origin/master
M	trevari/cron_log/cron_job_2019_11_15_11:00.log
브랜치가 'origin/master'에 맞게 업데이트된 상태입니다.
[LOG]: get_trevari_books.py is executed on 20:00:03
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', NameError("name 'book_name' is not defined",))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', IndexError('list index out of range',))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
('Exception occured', TypeError("'NoneType' object has no attribute '__getitem__'",))
[LOG]: get_trevari_books.py is finished on 21:56:46.
[LOG]: diff: diff --git a/trevari/trevari_book_list.md b/trevari/trevari_book_list.md
[LOG]: dir: /home/ubuntu/project/web_crawlers/trevari pwd: /home/ubuntu/project/web_crawlers/trevari
